export const universities = [

    {
        "id": "1",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "2",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "3",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "4",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "5",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "6",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "7",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "8",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "9",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "10",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "11",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "12",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "13",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "14",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "15",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "16",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "17",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "18",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "19",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "20",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "21",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "22",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "23",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "24",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "25",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "26",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "27",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "28",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "29",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "30",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "31",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "32",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "33",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "34",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "35",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "36",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "37",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "38",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "39",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "40",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "41",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "42",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "43",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "44",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "45",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "46",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "47",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "48",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "49",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "50",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "51",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "52",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "53",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "54",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "55",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "56",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "57",
        "path": "/",
        "image": "/assets/images/universities/konstanz.png",
        "name": "University of Konstanz",
        "category": "Research University",
        "location": "Konstanz, Germany",
        "type": "Public",
        "area": "Germany",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "58",
        "path": "/",
        "image": "/assets/images/universities/cambridge.png",
        "name": "University of Cambridge",
        "category": "Research University",
        "location": "Cambridge, UK",
        "type": "Public",
        "area": "UK",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "59",
        "path": "/",
        "image": "/assets/images/universities/trinity.png",
        "name": "Trinity College Dublin",
        "category": "Research University",
        "location": "Dublin, Ireland",
        "type": "Public",
        "area": "Ireland",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "60",
        "path": "/",
        "image": "/assets/images/universities/stanford.png",
        "name": "Stanford University",
        "category": "Research University",
        "location": "California, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "61",
        "path": "/",
        "image": "/assets/images/universities/oxford.png",
        "name": "University of Oxford",
        "category": "Research University",
        "location": "Oxford, England",
        "type": "Public",
        "area": "England",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "62",
        "path": "/",
        "image": "/assets/images/universities/toronto.png",
        "name": "University of Toronto",
        "category": "Research University",
        "location": "Toronto, Canada",
        "type": "Public",
        "area": "Canada",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "63",
        "path": "/",
        "image": "/assets/images/universities/sydney.png",
        "name": "University of Sydney",
        "category": "Research University",
        "location": "Sydney, Australia",
        "type": "Public",
        "area": "Australia",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    },
    {
        "id": "64",
        "path": "/",
        "image": "/assets/images/universities/massachusetts.png",
        "name": "Massachusetts Institute of Technology",
        "category": "Research University",
        "location": "Massachusetts, USA",
        "type": "Private",
       "tag" : "private",
        "area": "USA",
        "specificAddress": "The Old Schools, Trinity Ln, Cambridge CB2 1TN, United Kingdom",
        "logo": "/assets/images/logo/cambridge-logo.png",
        "cover": "/assets/images/cover/cambridge-cover.png",
        "about": "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209 and granted a royal charter by Henry III in 1231, Cambridge is the world's third-oldest surviving university.",
        "universityAddress": "https://www.cam.ac.uk/"
    }

];